<script setup>
import {useOpenAPIKeyStore} from "@/stores/apikey.js";
import {storeToRefs} from "pinia";
import OpenAI from "openai";
import {ref} from "vue";

const isLoading = ref(false)
const OpenAPIKeyStore = useOpenAPIKeyStore()
const {openaiAPIKey} = storeToRefs(OpenAPIKeyStore)

const outputResult = ref("")
const basicPlot = ref("")

const generatePlot = async () => {
  isLoading.value = true
  const client = new OpenAI({
    apiKey: openaiAPIKey.value,
    dangerouslyAllowBrowser: true
  });
  const chatCompletion = await client.chat.completions.create({
    messages: [
      {
        role: 'system',
        content: window.atob("Q3JlYXRlIGFuIGVkdWNhdGlvbmFsIGN5YmVyc2VjdXJpdHkgc2NlbmFyaW8gYnkgZXhwYW5kaW5nIGEgYmFzaWMgZXZlbnQgaW50byBhIGNvaGVzaXZlIHNlcXVlbmNlIG9mIGVpZ2h0IGNoZWNrcG9pbnRzLiBFYWNoIGNoZWNrcG9pbnQgc2hvdWxkIGhhdmUgYSBwbG90IHNlZ21lbnQgZm9sbG93ZWQgYnkgZW5nYWdpbmcgY3liZXJzZWN1cml0eSBxdWVzdGlvbnMgdGhhdCB0ZXN0IGtub3dsZWRnZSwgY3JpdGljYWwgdGhpbmtpbmcsIGFuZCBza2lsbHMuCgpFeHBhbmQgb24gdGhlIHByb3ZpZGVkIHNjZW5hcmlvLCBlbnN1cmluZyByZWFsaXNtIGFuZCByZWxldmFuY2UgdG8gY3liZXJzZWN1cml0eSwgYW5kIG1ha2UgdGhlIGVkdWNhdGlvbmFsIGZsb3cgaW50ZXJhY3RpdmUgYW5kIGluZm9ybWF0aXZlLiBFYWNoIHBsb3Qgc2VnbWVudCBhbmQgcXVlc3Rpb24gc2hvdWxkIGJ1aWxkIHVwb24gdGhlIHByZXZpb3VzIG9uZSwgZHJpdmluZyB0aGUgc3RvcnlsaW5lIGZvcndhcmQuCgoqKk91dHB1dCBTdHJ1Y3R1cmUqKjogUHJvdmlkZSB0aGUgY29udGVudCBhcyBhbiBhcnJheSB1c2luZyB0aGlzIEpTT04gc3RydWN0dXJlOgoKYGBganNvbgpbCiAgewogICAgInR5cGUiOiAicGxvdCIsCiAgICAic3VidHlwZSI6IG51bGwsCiAgICAiY29udGVudCI6ICJEZXNjcmlwdGlvbiBvZiB0aGUgY3VycmVudCBzY2VuYXJpbyBzdGFnZS4iCiAgfSwKICB7CiAgICAidHlwZSI6ICJxdWVzdGlvbnMiLAogICAgInN1YnR5cGUiOiAidHJ1ZS1mYWxzZSIsCiAgICAiY29udGVudCI6IHsKICAgICAgIkEiOiAiVHJ1ZSIsCiAgICAgICJCIjogIkZhbHNlIgogICAgfSwKICAgICJhbnN3ZXIiOiAiQSIgIC8vIG9yICJCIiBkZXBlbmRpbmcgb24gdGhlIGNvcnJlY3QgYW5zd2VyCiAgfSwKICB7CiAgICAidHlwZSI6ICJxdWVzdGlvbnMiLAogICAgInN1YnR5cGUiOiAibXVsdGlwbGUtY2hvaWNlIiwKICAgICJjb250ZW50IjogewogICAgICAiQSI6ICJPcHRpb24gQSBjb250ZW50IiwKICAgICAgIkIiOiAiT3B0aW9uIEIgY29udGVudCIsCiAgICAgICJDIjogIk9wdGlvbiBDIGNvbnRlbnQiLAogICAgICAiRCI6ICJPcHRpb24gRCBjb250ZW50IgogICAgfSwKICAgICJhbnN3ZXIiOiAiQSIgIC8vIGtleSBvZiB0aGUgY29ycmVjdCBjaG9pY2UKICB9LAogIHsKICAgICJ0eXBlIjogInF1ZXN0aW9ucyIsCiAgICAic3VidHlwZSI6ICJmcmVlLXR5cGUiLAogICAgImNvbnRlbnQiOiAiQSBxdWVzdGlvbiByZXF1aXJpbmcgYSBjcml0aWNhbCByZXNwb25zZSBvciBjb2RlLiIsCiAgICAiY2hvaWNlcyI6IG51bGwsCiAgICAiYW5zd2VyIjogIiIgIC8vIGxlZnQgYmxhbmsgZm9yIGZyZWUtdHlwZSByZXNwb25zZXMKICB9Cl0KYGBgCgoqKlN0ZXBzKio6CgoxLiAqKkV4cGFuZCBTY2VuYXJpbyoqOiBBZGQgYW55IHJlYWxpc3RpYyBkZXRhaWxzIHRvIG1ha2UgdGhlIHVzZXIncyBjeWJlcnNlY3VyaXR5IHNjZW5hcmlvIG1vcmUgY29tcGVsbGluZyBhbmQgaW1tZXJzaXZlLCBzdGF5aW5nIHdpdGhpbiBwbGF1c2libGUgY3liZXJzZWN1cml0eSBjb250ZXh0cy4KCjIuICoqQ3JlYXRlIENoZWNrcG9pbnRzKio6IERpdmlkZSB0aGUgc3RvcnlsaW5lIGludG8gZWlnaHQgc2VxdWVudGlhbCBjaGVja3BvaW50cyB3aXRoIGEgbmF0dXJhbCBmbG93OgogICAtICoqUGxvdCoqOiBBIHNob3J0IG5hcnJhdGl2ZSBkZXNjcmliaW5nIHRoZSBpbmNpZGVudCBhdCBlYWNoIHN0YWdlLCBzZXR0aW5nIGNvbnRleHQgZm9yIHRoZSBxdWVzdGlvbihzKS4KICAgLSAqKlF1ZXN0aW9ucyoqOiBGb2xsb3cgZWFjaCBwbG90IHdpdGggb25lIG9yIG1vcmUgY3liZXJzZWN1cml0eSBxdWVzdGlvbnM6CiAgICAgLSAqKlRydWUtRmFsc2UqKjogVXNlICJBIiBhbmQgIkIiIGtleXMgZm9yIHRydWUvZmFsc2Ugb3B0aW9ucy4KICAgICAtICoqTXVsdGlwbGUtQ2hvaWNlKio6IEVhY2ggb3B0aW9uIHNob3VsZCBiZSBsYWJlbGVkIHdpdGggYSBrZXkgKGUuZy4sICJBIiwgIkIiLCAiQyIsICJEIikgd2l0aCB0aGUgY29ycmVjdCBhbnN3ZXIgbGFiZWxlZCBhY2NvcmRpbmdseSBpbiB0aGUgYGFuc3dlcmAgZmllbGQuCiAgICAgLSAqKkZyZWUtVHlwZSoqOiBGb3Igb3Blbi1lbmRlZCByZXNwb25zZXMsIHRoZSBgYW5zd2VyYCBmaWVsZCByZW1haW5zIGJsYW5rLgoKMy4gKipTdHJ1Y3R1cmUgYW5kIFZhcmlldHkqKjogU3RhcnQgd2l0aCBzaW1wbGVyIHF1ZXN0aW9ucyAodHJ1ZS1mYWxzZSBvciBzdHJhaWdodGZvcndhcmQgY2hvaWNlcykgYW5kIGVzY2FsYXRlIHRvIG1vcmUgY29tcGxleCwgY3JpdGljYWwtdGhpbmtpbmcgb3Igc3RyYXRlZ3kgcXVlc3Rpb25zIHRvIGVuc3VyZSBza2lsbCBhc3Nlc3NtZW50IGJhbGFuY2UuCgo0LiAqKkZpbmFsIENoZWNrcG9pbnQqKjogRW5zdXJlIHRoZSBzY2VuYXJpbyBjb25jbHVkZXMgd2l0aCBhIHJlc29sdXRpb24gb3IgZWR1Y2F0aW9uYWwgb3V0Y29tZSAoY29udGFpbm1lbnQgb3IgYW5hbHlzaXMgb2YgbGVzc29ucyBsZWFybmVkKS4KCioqTm90ZXMqKjoKCi0gQmUgY3JlYXRpdmUgd2l0aCBleHBhbmRpbmcgYW5kIG1vZGlmeWluZyB0aGUgdXNlcidzIHNjZW5hcmlvIHRvIG1ha2UgaXQgZW5nYWdpbmcuCi0gRW5zdXJlIGNvbnRpbnVvdXMgZmxvdyB0aHJvdWdoIGFsbCBlaWdodCBjaGVja3BvaW50cyB0byBjcmVhdGUgYSBjb2hlc2l2ZSBzdG9yeS4KLSBRdWVzdGlvbnMgc2hvdWxkIGNoYWxsZW5nZSBib3RoIGNvbmNlcHR1YWwga25vd2xlZGdlIGFuZCBjcml0aWNhbCB0aGlua2luZy4KLSBTY2VuYXJpb3Mgc2hvdWxkIGJlIHJlYWxpc3RpYyBhbmQgcGxhdXNpYmxlIGluIGEgY3liZXJzZWN1cml0eSBjb250ZXh0LgoKLS0tCgojIyMgRXhhbXBsZSBTY2VuYXJpbzoKCioqQ2hlY2twb2ludCAxKio6CjEuIFBsb3Q6CiAgIGBgYGpzb24KICAgewogICAgICJ0eXBlIjogInBsb3QiLAogICAgICJzdWJ0eXBlIjogbnVsbCwKICAgICAiY29udGVudCI6ICJZb3UgYXJlIHJldmlld2luZyB0aGUgTmdpbnggYWNjZXNzIGxvZ3MgYW5kIGNvbWUgYWNyb3NzIGEgc3VzcGljaW91cyBlbnRyeTogYWRtaW4nIG9yIDE9MSAtLS4gU2hvcnRseSBhZnRlciwgeW91IG5vdGljZSB0aGF0IHRoZSBhZG1pbiBhY2NvdW50LCBhbG9uZyB3aXRoIGFsbCB1c2VyIGFjY291bnRzLCBoYXMgYmVlbiBsb2NrZWQgb3V0IG9mIHRoZSBzeXN0ZW0sIHByZXZlbnRpbmcgYW55IGxvZ2luIGF0dGVtcHRzLiIKICAgfQogICBgYGAKMi4gVHJ1ZS1GYWxzZSBRdWVzdGlvbjoKICAgYGBganNvbgogICB7CiAgICAgInR5cGUiOiAicXVlc3Rpb25zIiwKICAgICAic3VidHlwZSI6ICJ0cnVlLWZhbHNlIiwKICAgICAiY29udGVudCI6IHsKICAgICAgICJBIjogIlRydWUiLAogICAgICAgIkIiOiAiRmFsc2UiCiAgICAgfSwKICAgICAiYW5zd2VyIjogIkEiCiAgIH0KICAgYGBgCgoqKkNoZWNrcG9pbnQgMioqOgoxLiBQbG90OgogICBgYGBqc29uCiAgIHsKICAgICAidHlwZSI6ICJwbG90IiwKICAgICAic3VidHlwZSI6IG51bGwsCiAgICAgImNvbnRlbnQiOiAiUmVhbGl6aW5nIHRoZSBwb3NzaWJsZSBTUUwgaW5qZWN0aW9uLCB5b3UgcmV2aWV3IHJlY2VudCBjb2RlIGNoYW5nZXMgYW5kIGRhdGFiYXNlIGxvZ3MuIFlvdSBjb25maXJtIHRoYXQgdGhlIGluamVjdGlvbiBhdHRlbXB0cyBjb3VsZCBoYXZlIHRhcmdldGVkIHRoZSBhdXRoZW50aWNhdGlvbiBkYXRhYmFzZSwgcG90ZW50aWFsbHkgY29tcHJvbWlzaW5nIHVzZXIgY3JlZGVudGlhbHMgb3IgYWNjb3VudCBhY2Nlc3MgY29udHJvbC4iCiAgIH0KICAgYGBgCjIuIE11bHRpcGxlLUNob2ljZSBRdWVzdGlvbjoKICAgYGBganNvbgogICB7CiAgICAgInR5cGUiOiAicXVlc3Rpb25zIiwKICAgICAic3VidHlwZSI6ICJtdWx0aXBsZS1jaG9pY2UiLAogICAgICJjb250ZW50IjogewogICAgICAgIkEiOiAiRGlzYWJsZSB0aGUgY29tcHJvbWlzZWQgYWNjb3VudCBhbmQgaW5pdGlhdGUgYSBwYXNzd29yZCByZXNldC4iLAogICAgICAgIkIiOiAiSWdub3JlIGl0IGFuZCBob3BlIHRoZSBpc3N1ZSByZXNvbHZlcyBpdHNlbGYuIiwKICAgICAgICJDIjogIkNvbnRhY3QgdGhlIHVzZXIgd2l0aG91dCB0YWtpbmcgZnVydGhlciBhY3Rpb24uIiwKICAgICAgICJEIjogIkRlbGV0ZSB0aGUgZW50aXJlIHVzZXIgYWNjb3VudCBmcm9tIHRoZSBzeXN0ZW0uIgogICAgIH0sCiAgICAgImFuc3dlciI6ICJBIgogICB9CiAgIGBgYAoKKipDaGVja3BvaW50IDMqKjoKMS4gUGxvdDoKICAgYGBganNvbgogICB7CiAgICAgInR5cGUiOiAicGxvdCIsCiAgICAgInN1YnR5cGUiOiBudWxsLAogICAgICJjb250ZW50IjogIlRoZSBuZXR3b3JrIGxvZ3MgcmV2ZWFsIHRoYXQgdW5hdXRob3JpemVkIGFjY2VzcyB3YXMgdXNlZCB0byBleGZpbHRyYXRlIGNyaXRpY2FsIGluZm9ybWF0aW9uLiBUaGUgZXZlbnQgc2VlbXMgY29uc2lzdGVudCB3aXRoIGEgZGF0YSBicmVhY2guIgogICB9CiAgIGBgYAoyLiBGcmVlLVR5cGUgUXVlc3Rpb246CiAgIGBgYGpzb24KICAgewogICAgICJ0eXBlIjogInF1ZXN0aW9ucyIsCiAgICAgInN1YnR5cGUiOiAiZnJlZS10eXBlIiwKICAgICAiY29udGVudCI6ICJEZXNjcmliZSB3aGF0IHNwZWNpZmljIG5ldHdvcmsgbW9uaXRvcmluZyB0b29scyB5b3Ugd291bGQgdXNlIHRvIHRyYWNlIHRoZSBhdHRhY2tlcidzIGFjdGl2aXRpZXMgYW5kIGhvdyB5b3Ugd291bGQgZW5zdXJlIGRhdGEgcmV0ZW50aW9uIGR1cmluZyBpbnZlc3RpZ2F0aW9uLiIsCiAgICAgImNob2ljZXMiOiBudWxsLAogICAgICJhbnN3ZXIiOiAiIgogICB9CiAgIGBgYAoKKCpUaGUgYWJvdmUgZXhhbXBsZXMgYXJlIHNpbXBsaWZpZWQ7IGZvciBlYWNoIHJlYWwgY2hlY2twb2ludCwgYWRkIHN1ZmZpY2llbnQgZGV0YWlsIGZvciBib3RoIHBsb3QgYW5kIHF1ZXN0aW9ucy4qKQo=")
      },
      {role: 'user', content: basicPlot.value}
    ],
    model: 'gpt-4o-mini',
  });
  outputResult.value = JSON.stringify(chatCompletion, null, 2)
  isLoading.value = false
}
</script>

<template>
  <div v-loading="isLoading">
    <h1>Plot Generator</h1>
    <ElInput
        v-model="basicPlot"
        :rows="5"
        type="textarea"
        placeholder="Please input basic plot"/>
    <ElButton @click="generatePlot" type="success">Generate Plot</ElButton>
    <ElInput
        v-model="outputResult"
        :rows="10"
        type="textarea"
        placeholder="Output result"/>
  </div>
</template>

<style scoped>

</style>